config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')

  resources :welcome, only: [:index]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: %i[index show edit update destroy]
  resources :posts
  resources :friend_requests, only: %i[index create update destroy] do
    collection do
      get 'random'
    end
  end
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  # has_many :comments, through: :posts,
  #           source: :post
  has_many :likes
  has_many :active_friend_requests, class_name: 'FriendRequest',
                                    foreign_key: 'requestor_id',
                                    dependent: :destroy
  has_many :friends, -> { where('accepted = ?', true).references(:active_friend_requests) },
           through: :active_friend_requests,
           source: :requested
  has_many :passive_friend_requests, class_name: 'FriendRequest',
                                     foreign_key: 'requested_id',
                                     dependent: :destroy
  has_many :friends, -> { where('accepted = ?', true).references(:passive_friend_requests) },
           through: :passive_friend_requests,
           source: :requestor
  attr_reader :avatar_remote_url
  has_attached_file :avatar, styles: { timeline_photo: '900x1800' }, default_url: 'https://s3.amazonaws.com/malbrecht0792-odinfacebook-bucket/:style/missing.png'
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def self.search(first_name_search)
    where('lower(first_name) LIKE ?', "%#{first_name_search.downcase}%")
  end

  # Friends a user
  def friend(other_user)
    active_friend_requests.build(requestor_id: id,
                                 requested_id: other_user.id,
                                 accepted: false).save
    passive_friend_requests.build(requestor_id: other_user.id,
                                  requested_id: id,
                                  accepted: false).save
  end

  # Cancels friend request sent to another user
  def cancel_friend_request(other_user)
    active_friend_requests.find_by(requested_id: other_user.id).delete
    passive_friend_requests.find_by(requestor_id: other_user.id).delete
  end

  # Unfriends a user
  def unfriend(other_user)
    friends.delete(other_user)
  end

  # Returns true if the current user is friends with the other user.
  def friends?(other_user)
    friends.include?(other_user)
  end

  # Returns true if the current user has sent a friend request to the other user 
  # but it has not been accepted yet
  def request_sent?(current_user, other_user)
    unless other_user.nil?
      active_friend_requests.exists?(requestor_id: current_user.id,
                                     requested_id: other_user.id)
    end
  end

  def likes?(post)
    likes.exists?(post_id: post.id, user_id: id)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # assuming the user model has a first name
      user.first_name = auth.info.first_name
      # assuming the user model has a last name
      user.last_name = auth.info.last_name
      # user.avatar_file_name = auth.info.image
      # user.avatar = URI.parse(auth.info.image)
      # avatar_remote_url(auth.info.image)
      # user.avatar = auth.info.image_url # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def avatar_remote_url=(url_value)
    self.avatar = URI.parse(url_value)
    # Assuming url_value is http://example.com/photos/face.png
    # avatar_file_name == 'face.png'
    # avatar_content_type == 'image/png'
    @avatar_remote_url = url_value
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super
    UserMailer.sign_up_confirmation_email(@user).deliver_now if @user.persisted?
  end

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update]

  def index
    @users = User.search(params[:user_search])
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      puts @user.errors.full_messages
    end
  end

  def show
    @post = current_user.posts.build
    @posts = @user.posts.order('posts.created_at DESC')
  end

  private

  def set_user
    @user = if !params[:id].nil?
              User.find(params[:id])
            else
              current_user
            end
  end

  def user_params
    params.require(:user).permit(:email, :encrypted_password, :avatar)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end

  def full_name(user)
    "#{user.first_name} #{user.last_name}"
  end
  
end

app/views/users/_comments.html.erb
<% if post.comments.count > 0 %>
	<% post.comments.each do |comment| %>
		<div class="comments-form">
			<span class="author-name">
				<li><%= link_to full_name(comment.author), 
						comment.author, {:style=>"color: #365899;"} %></li>
			</span>
			<span class="comments"><%= comment.content %></span>
		</div>
	<% end %>
<% end %>
<%= form_tag comments_path, :method => 'post' do %>
	<div class="new-comment-form">
		<div class="input-group">
			<%= text_field_tag(:content, "", class: "form-control", placeholder: "Comment...") %>
			<span class="input-group-btn">
				<%= submit_tag("Comment", class: "btn btn-default") %>
			</span>
			<input type="hidden" name="post_id" value=<%= post.id %>>
		</div>
	</div>
<%end%>

app/views/users/_friend.html.erb
<%= form_tag friend_requests_path, :method => 'post' do %>
	<% if !@user.nil? %>
		<input type="hidden" name="requested_id" value=<%= @user.id %>>
	<% end %>
	<%= submit_tag("Add Friend", class: "friend-request-button") %>
<% end %>

app/views/users/_friend_request_form.html.erb
<div id="friend_form">
	<% if current_user.friends?(@user) %>
		<%= render 'users/unfriend' %>
	<% elsif current_user.request_sent?(current_user, @user) %>
		<%= render 'users/sent' %>
	<% else %>
		<%= render 'users/friend' %>
	<% end %>
</div>

app/views/users/_like.html.erb
<%= form_tag likes_path, :method => 'post' do %>
	<input type="hidden" name="post_id" value=<%= post.id %>>
	<%= submit_tag("Like", class: "like-button") %>
<% end %>

app/views/users/_like_form.html.erb
<% if current_user.likes?(post) %>
	<%= render 'users/unlike', post: post %>
<% else %>
	<%= render 'users/like', post: post %>
<% end %>

app/views/users/_posts.html.erb
<% if post.comments.count > 0 %>
	<% post.comments.each do |comment| %>
		<div class="comments-form">
			<span class="author-name">
				<li><%= link_to "#{comment.author.first_name} #{comment.author.last_name}", 
						comment.author, {:style=>"color: #365899;"} %></li>
			</span>
			<span class="comments"><%= comment.content %></span>
		</div>
	<% end %>
<% end %>
<%= form_tag comments_path, :method => 'post' do %>
	<div class="new-comment-form">
		<div class="input-group">
			<%= text_field_tag(:content, "", class: "form-control", placeholder: "Comment...") %>
			<span class="input-group-btn">
				<%= submit_tag("Comment", class: "btn btn-default") %>
			</span>
			<input type="hidden" name="post_id" value=<%= post.id %>>
		</div>
	</div>
<%end%>

app/views/users/_profile_new_post.html.erb
<% if @user == current_user %>
  <div class="new-post">
    <%= form_for @post, :url => posts_path, :html => {:method => :create} do |f| %>
      <%= f.label(:content, "New Post", class: "new-post-label") %>
      <%= f.text_area(:content, rows: "4", class: 'new-post-form') %>
      <input type="hidden" name="id" value=<%= params[:id] %>>

      <%= f.submit("Post", class: "new-post-button") %>
    <% end %>
  </div>
<% end %>

app/views/users/_profile_page_header.html.erb
<div class="image1 timeline-photo">
  <span class"timeline-photo-size">
    <%= image_tag @user.avatar.url(:timeline_photo) %>
  </span>
  <h1 class="profile-name">
    <%= full_name(@user) %>
  </h1>
  <div class="image2">
    <%= gravatar_for @user, size: 180%>
  </div>
  <%= render 'users/friend_request_form' if @user != current_user %>
</div>

app/views/users/_sent.html.erb
<%= form_for(current_user.active_friend_requests.find_by(requested_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Request Sent", class: "friend-request-button" %>
<% end %>

app/views/users/_unfriend.html.erb
<%= form_for(current_user.active_friend_requests.find_by(requested_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfriend", class: "friend-request-button" %>
<% end %>

app/views/users/_unlike.html.erb
<%= form_for(post.likes.find_by(user_id: current_user.id), 
			html: { method: :delete },
			remote: true) do |f| %>
	<%= f.submit("Unlike", class: "unlike-button") %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users Search Results</h1>

<% @users.each do |user| %>
	<p>
		<%= link_to "#{user.first_name} #{user.last_name}", user_path(user.id)%>
	</p>
<% end %>

app/views/users/show.html.erb
<%= render 'profile_page_header' %>

<%= render 'profile_new_post' %>

<%= render 'shared/posts' %>