config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')

  resources :welcome, only: [:index]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: %i[index show edit update destroy]
  resources :posts
  resources :friend_requests, only: %i[index create update destroy] do
    collection do
      get 'random'
    end
  end
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :requestor, class_name: 'User'
  belongs_to :requested, class_name: 'User'
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  def index
    @users = User.joins(:active_friend_requests).where(friend_requests: { requested_id: current_user.id, accepted: false })
  end

  def create
    @user = User.find(params[:requested_id])
    current_user.friend(@user)
    redirect_to @user
  end

  def update
    @friend_request1 = FriendRequest.find(params[:id])
    @friend_request2 = FriendRequest.find(params[:id].to_i + 1)
    @friend_request1.update_attributes(accepted: true)
    @friend_request2.update_attributes(accepted: true)
    redirect_to friend_requests_url
  end

  def destroy
    @user = FriendRequest.find(params[:id]).requested
    current_user.cancel_friend_request(@user)
    redirect_to @user
  end

  def random
    user = User.find(rand(1...500))
    if user != current_user && !user.friends?(current_user) && !user.request_sent?(current_user, user)
      user.friend(current_user)
      redirect_to friend_requests_url
    else
      random
    end
  end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/index.html.erb
<h1>Friend Requests</h1>

<%= form_tag random_friend_requests_path, :method => 'get' do %>
	<div class="new-comment-form">
		<div class="input-group">
			<p class="form-control friend-request-text">Generate random friend request</p>
			<span class="input-group-btn">
				<%= submit_tag("Create", class: "btn btn-default") %>
			</span>
		</div>
	</div>
<%end%>

<% @users.each do |user| %>

	<%= form_for(current_user.passive_friend_requests.find_by(requestor_id: user.id),
             													  html: { method: :patch },
             													  remote: true) do |f| %>
		<div class="new-comment-form">
			<div class="input-group">
				<p class="form-control friend-request-text">
					<%= full_name(user) %>
				</p>
				<span class="input-group-btn">
					<%= f.submit "Accept", class: "btn btn-default" %>
				</span>
			</div>
		</div>
	<%end%>
<% end %>