config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')

  resources :welcome, only: [:index]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: %i[index show edit update destroy]
  resources :posts
  resources :friend_requests, only: %i[index create update destroy] do
    collection do
      get 'random'
    end
  end
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse header">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
        <li><%= link_to "Home", posts_path %></li>
      </ul>
      <div class="navbar-form navbar-left">
        <%= form_tag users_path, :method => 'get' do %>
          <div class="search-bar">
            <div class="input-group">
              <%= text_field_tag(:user_search, "", class: "form-control", placeholder: "Search") %>
              <span class="input-group-btn">
                <%= submit_tag("Go", class: "btn btn-default") %>
              </span>
            </div>
          </div>
        <%end%>
      </div>
    
      <ul class="nav navbar-nav navbar-right header-links"> 
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Home", posts_path %></li>
        <li><%= link_to "Friend Requests", friend_requests_path %></li>
        <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
      </ul> 
    </div> <!-- .navbar-collapse -->
   </div>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless controller_name == "sessions" && action_name == "new" %>
      
      <%= render 'layouts/header' %>
      <div id="container">
        <% flash.each do |message_type, message| %>
          <% puts "MESSAGE TYPE: #{message_type}" %>
          <div class="alert <%= bootstrap_class_for(message_type) %> fade in">
            <button class="close" data-dismiss="alert">×</button>
            <%= message %>
          </div>
          <% puts "MESSAGE TYPE: #{message_type}" %>
        <%end%>
      </div>

      <% else %>

    	<div id="container">
    		<% flash.each do |message_type, message| %>
          <% puts "MESSAGE TYPE: #{message_type}" %>
          <div class="alert <%= bootstrap_class_for(message_type) %> fade in login-flash">
            <button class="close" data-dismiss="alert">×</button>
            <%= message %>
          </div>
          <% puts "MESSAGE TYPE: #{message_type}" %>
    		<%end%>
    	</div>

    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/login_page.html.erb
<% content_for :stylesheets do %>
      #navbar {display: none}
<% end %>
<%= render :template => "layouts/application" %>